### ISSUE TITLE
version 1.0.0 and 1.0.1 do not contain any js content

### ISSUE THREAD

**Issue by arlac77** [silverwind/rebirth#4]
Error: Cannot find module 'rebirth'
    at Function.Module._resolveFilename (module.js:485:15)
    at Function.Module._load (module.js:437:25)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)

**Comment by silverwind** [comment]
Whoops, forgot to update `files` when renaming. Fixed in v1.0.2.
